test.support.catch\_unraisable\_exception
=========================================

.. currentmodule:: test.support

.. autoclass:: catch_unraisable_exception
   :members:
   :show-inheritance:
   :inherited-members:

   
   .. automethod:: __init__

   
   .. rubric:: Methods

   .. autosummary::
   
      ~catch_unraisable_exception.__init__
   
   

   
   
   